version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH /home/docs/.local/bin/poetry install

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
