name: CI

on:
  pull_request:

jobs:
  tests:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install tox
        run: pipx install tox
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Run tests
        run: tox -e py${{ matrix.python-version }}

  formatting:
    name: Check formatting
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install tox
        run: pipx install tox
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'
      - name: Run formatting checks
        run: tox -e format

  typecheck:
    name: Check types
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install tox
        run: pipx install tox
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run formatting checks
        run: tox -e typecheck

  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install tox
        run: pipx install tox
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'
      - name: Run linting checks
        run: tox -e lint

  docs:
    name: Check docs for warnings
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install tox
        run: pipx install tox
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'
      - name: Build documentation
        run: tox -e docs
